### ISSUE TITLE
test.py lost 'IdLookupTable.csv'

### ISSUE THREAD

**Issue by kobewangSky** [ahmorsi/FacialKeypointsDetection#1]
Hi there 
I test your keras code and I run the test.py
but I can not find IdLookupTable.csv
How can I get That?
Thanks,
Kobe

**Comment by ahmorsi** [comment]
Hi Kobe,

It is already provided by Kaggle
<https://www.kaggle.com/c/facial-keypoints-detection/data>and I mentioned
that in README. Do you think the description was not clear enough ?

Regards,
Ahmed

**Comment by kobewangSky** [comment]
Hi Ahmed

I see It !!!
I am fist time use kaggle, so I did not notice.
Thanks!!

Kobe.
